# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 有心言者 # 网站标题
email: zhurong0525@icloud.com # 邮箱地址
description: >- # this means to ignore newlines until "baseurl:"
  分享技术、思考和生活点滴。 # 网站描述
baseurl: "" # the subpath of your site, e.g. /blog。 如果您的网站部署在根目录，留空即可。
url: "https://aronghome.us.kg" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  zhurong0525 # Twitter 用户名
github_username:  zhurong2020 # GitHub 用户名

# Minimal Mistakes settings (主题相关设置)
minimal_mistakes_skin: default # 主题配色方案，可选：default, dark, air, contrast, dirt, neon, mint, etc.
search: true # 启用站内搜索

# Build settings
theme: minimal-mistakes-jekyll # 确保使用了该主题
plugins:
  - jekyll-feed
  - jekyll-seo-tag # 建议添加 jekyll-seo-tag 插件

# Pagination (分页设置)
paginate: 5 # 每页显示的文章数量
paginate_path: /page:num/ # 分页链接的格式

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    line_numbers: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections (集合设置)
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Defaults (默认值设置)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

sass:
  sass_dir: _sass
  style: compressed
