# Cloudflare Images 配置
image_processing:
  cloudflare:
    api_base_url: "https://api.cloudflare.com/client/v4/accounts/{account_id}/images/v1"
    variants:
      - width: 600
        quality: 75
      - width: 1200
        quality: 80
        name: "header"
    mapping_file: "_data/image_mappings.yml"
    retry:
      max_attempts: 3
      initial_delay: 1.0
      max_delay: 10.0 