# AI 内容处理配置
content_processing:
  gemini:
    model: "gemini-2.5-pro"  # 使用的模型名称
    temperature: 0.7     # 生成的随机性 (0.0-1.0)
    max_output_tokens: 4096  # 最大输出长度
    top_p: 0.8          # 采样概率阈值
    prompts:
      polish: "请润色以下文章，保持原意的同时使语言更加流畅自然。"
      test: |
        请按照以下规范生成一篇用于测试的技术博客文章：

        【内容要求】
        1. 选择一个当前热门的技术话题（如AI、区块链、量子计算等）
        2. 文章长度800-1000字，确保内容完整
        3. 使用"你知道吗?"开场，科普化语调
        4. 包含2-3个具体数据或案例
        5. 必须有完整的结尾，不能中途截断

        【文章结构】
        1. 标题：25-35字吸引人的中文标题（确保3×2网格显示效果）
        2. 50-60字简洁引言（匹配excerpt要求，突出核心价值）
        3. "<!-- more -->" 标签
        4. 3-4个主要段落（每段120-180字）
        5. 🎧 播客收听部分（1段简化版）
        6. 🌍 英文原始资料部分（3-5个相关链接）
        7. 完整结尾段落

        【格式要求】
        - 直接输出文章正文内容，不要包含YAML front matter
        - 不要包含任何解释性语句如"好的"、"遵照规范"等
        - 不要使用代码块包装内容
        - 文章必须完整，有明确的开头和结尾
        - 控制在40-50行左右

        请直接生成文章内容：
    retry:
      max_attempts: 3
      initial_delay: 1.0
      max_delay: 10.0
    # ... 其他 Gemini 配置 