# AI 内容处理配置
content_processing:
  gemini:
    model: "gemini-2.5-pro"  # 使用的模型名称
    temperature: 0.7     # 生成的随机性 (0.0-1.0)
    max_output_tokens: 2048  # 最大输出长度
    top_p: 0.8          # 采样概率阈值
    prompts:
      polish: "请润色以下文章，保持原意的同时使语言更加流畅自然。"
      test: "请生成一篇关于自动化测试的技术博客文章，包含实践经验和最佳实践。"
    retry:
      max_attempts: 3
      initial_delay: 1.0
      max_delay: 10.0
    # ... 其他 Gemini 配置 